CREATE TABLE packs (
  id bigint generated by default as identity primary key,
  name character varying(255),
  description character varying(255),
  keywords character varying(255),
  fulltext tsvector generated always as (to_tsvector('english'::regconfig, (((name::text || ' '::text) || COALESCE(description, ''::character varying)::text) || ' '::text) || COALESCE(keywords, ''::character varying)::text)) stored
);

CREATE INDEX IF NOT EXISTS packs_fulltext_idx ON packs USING GIN (fulltext);